// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcvguxujgljxxhdvsbwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjdmd1eHVqZ2xqeHhoZHZzYndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTMyNjYsImV4cCI6MjA2NDk4OTI2Nn0.7fGwEp6XK7Gnw6UcDOLKpq6bDiD5xf6ZLtRPcomPuvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);